name: forgottenlandapp_etl
description: Forgotten Land App ETL
version: 25.09.27+1
publish_to: none

environment:
  sdk: "3.6.0"

dependencies:
  forgottenlandapp_models:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-models"
      ref: master
  forgottenlandapp_utils:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-utils"
      ref: master
  forgottenlandapp_adapters:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-adapters"
      ref: master
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  http: ^0.13.0
  lints: ^4.0.0
  test: ^1.15.0
