name: forgottenlandapp_etl
description: Forgotten Land App ETL
version: 25.10.01+1
publish_to: none

environment:
  sdk: "3.6.0"

dependencies:
  forgottenlandapp_models:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-models"
      ref: master
  forgottenlandapp_utils:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-utils"
      ref: master
  forgottenlandapp_adapters:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-adapters"
      ref: master
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0

dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^4.1.1
  http: ^1.5.0
  lints: ^5.1.1
  test: ^1.15.0
